feat: add update of partitions
electric-saw/kafta pull request #30
Opened 2024-12-20 21:03 UTC by Mario-Valente

resolve this issue https://github.com/electric-saw/kafta/issues/29

2024-12-23 13:30 UTC, snakeice commented
How about creating a separate command for `resize`? It might also be a good idea to add a safeguard to warn about potential order loss, unless a flag like `-y` is used to skip confirmation. What do you think?

2024-12-23 13:37 UTC, Mario-Valente commented
> How about creating a separate command for `resize`? It might also be a good idea to add a safeguard to warn about potential order loss, unless a flag like `-y` is used to skip confirmation. What do you think?

I liked the idea, it makes sense, the user knows that they are different operations

2024-12-23 14:43 UTC, fellipesena requested changes

2024-12-23 14:43 UTC, fellipesena commented on internal/pkg/kafka/topic_config.go
> +		if key == "num.partitions" {
acho que valeria a pena fazer o tratamento aqui, não?

tipo:
```go
if key == "num.partitions" {
    if err = increasePartitions(conn, topic, props[key]); err != nil {
        return err
    } 
    continue
}
```

daí dentro do método trataria a conversão pra inteiro e etc

isso tira todo o pedaço de código de tratamento dessa func, adicionando bem menos complexidade pra cá que deveria ser genérico

2024-12-23 14:43 UTC, fellipesena commented on internal/pkg/kafka/topic_config.go
> +	if numPartitions, ok := props["num.partitions"]; ok {
eu tiraria esse tratamento e colocaria tudo direto no increasePartitions, ou até mesmo pode ter uma outra func pra tratar esse carinha e depois passar pra o increase partitions, mas não deixaria aqui pois não é bem o objetivo dessa func

2024-12-23 14:53 UTC, Mario-Valente commented on internal/pkg/kafka/topic_config.go
> +	if numPartitions, ok := props["num.partitions"]; ok {
Acredito que vai ser melhor  refatorar discutido na thread acima do @snakeice , e criar um subcomando de resize do tópico, dai essa validação não vai ser mais necessaria

2024-12-26 14:44 UTC, snakeice commented on pkg/cmd/cli/topic/topic_resize.go
> +		Use:   "resize NAME num.partitions=VALUE [--quiet]",
```suggestion
		Use:   "resize NAME PARTITIONS [--quiet]",
```

2024-12-30 18:33 UTC, snakeice approved these changes

2024-12-31 13:36 UTC, merged